### ISSUE TITLE
Error output when I run all_datasets_training.py

### ISSUE THREAD

**Issue by Usmankhujaev** [titu1994/LSTM-FCN#27]
Traceback (most recent call last):
  File "/home/lidar/projects/LSTM-FCN/all_datasets_training.py", line 268, in <module>
    train_model(model, did, dataset_name_, epochs=2000, batch_size=128,
  File "/home/lidar/projects/LSTM-FCN/utils/keras_utils.py", line 63, in train_model
    X_train, y_train, X_test, y_test, is_timeseries = load_dataset_at(dataset_id,
  File "/home/lidar/projects/LSTM-FCN/utils/generic_utils.py", line 65, in load_dataset_at
    y_train = (y_train - y_train.min()) / (y_train.max() - y_train.min()) * (nb_classes - 1)
TypeError: unsupported operand type(s) for -: 'str' and 'str'

I have this error after running the all_datasets_training.py
can you help me fixing this?

**Comment by Usmankhujaev** [comment]
please help it's urgent
